### ISSUE TITLE
Cannot read properties of undefined (reading 'charAt')

### ISSUE THREAD

**Issue by xiuber** [dragonir/3d#28]
Cannot read properties of undefined (reading 'charAt')

**Comment by dragonir** [comment]
什么情况下报的这个错误

**Comment by xiuber** [comment]
启动

**Comment by xiuber** [comment]
TypeError: Cannot read properties of undefined (reading 'charAt')
    at new Lexer (F:\MakerONE_#D\3d-master\node_modules\stylus\lib\lexer.js:78:23)
    at new Parser (F:\MakerONE_#D\3d-master\node_modules\stylus\lib\parser.js:158:18)
    at getDependencies (F:\MakerONE_#D\3d-master\node_modules\stylus-loader\dist\utils.js:166:18)
    at F:\MakerONE_#D\3d-master\node_modules\stylus-loader\dist\utils.js:379:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async F:\MakerONE_#D\3d-master\node_modules\stylus-loader\dist\utils.js:383:5
    at async Promise.all (index 0)
    at async createEvaluator (F:\MakerONE_#D\3d-master\node_modules\stylus-loader\dist\utils.js:348:3)
